//
//  Clipping.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 02/02/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Simpl.Serialization.Attributes;
using ecologylab.semantics.metadata.builtins.declarations;
using ecologylab.semantics.metametadata;

namespace ecologylab.semantics.metadata.builtins 
{
    [SimplInherit]
	public class Clipping : ClippingDeclaration
	{

		public Clipping() { }

		public Clipping(MetaMetadataCompositeField mmd) : base(mmd) { }

	}
}
