//
// ImageClipping.cs
// s.im.pl serialization
//
// Generated by DotNetTranslator on 10/19/11.
// Copyright 2011 Interface Ecology Lab. 
//


using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;
using ecologylab.collections;
using ecologylab.semantics.metadata;
using ecologylab.semantics.metadata.builtins.declarations;
using ecologylab.semantics.metadata.scalar;
using ecologylab.semantics.metametadata;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace ecologylab.semantics.metadata.builtins 
{
	[SimplInherit]
	public class ImageClipping : ImageClippingDeclaration
	{

		public ImageClipping() { }

		public ImageClipping(MetaMetadataCompositeField mmd) : base(mmd) { }

        public ImageClipping(MetaMetadataCompositeField metaMetadata, Image clippedMedia, Document source, Document outlink, String caption, String context) : this(metaMetadata)
	    {
		    MediaClipping<Image>.InitMediaClipping(this, clippedMedia, source, outlink, caption, context);
	    }

        public override bool IsImage
        {
            get
            {
                return true;
            }
        }

        public ImageSource ImageLocation
        {
            get
            {
                ImageSource result = null;
                if (this.Media != null)
                {
                    String uri = (this.Media.LocalLocation != null) ? this.Media.LocalLocation.Value.AbsoluteUri : this.Media.Location.Value.AbsoluteUri;
                    result = new BitmapImage(new Uri(uri));
                }
                return result;
            }
        }
	}
}
