//
//  MetadataClassDescriptor.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;
using Simpl.Serialization;
using System.Reflection;

namespace Ecologylab.BigSemantics.MetadataNS 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
	public class MetadataClassDescriptor : ClassDescriptor
	{

        public MetadataClassDescriptor(Type thatClass)
            :base(thatClass)
        {

        }

        //protected override FieldDescriptor NewFieldDescriptor(ClassDescriptor classDescriptor, FieldInfo fieldInfo, Int16 annotationType)
        //{
        //    return new MetadataFieldDescriptor(classDescriptor, fieldInfo, annotationType);
        //}
	}
}
