//
// LinkWith.cs
// s.im.pl serialization
//
// Generated by DotNetTranslator on 10/14/11.
// Copyright 2011 Interface Ecology Lab. 
//


using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using Simpl.Serialization.Types.Element;
using System;
using System.Collections;
using System.Collections.Generic;
using Ecologylab.Collections;

namespace Ecologylab.BigSemantics.MetaMetadataNS 
{
	[SimplInherit]
	public class LinkWith : ElementState, IMappable<String>
	{
		[SimplScalar]
		[SimplHints(new Hint[] {Hint.XmlAttribute})]
		private String name;

		[SimplScalar]
		[SimplHints(new Hint[] {Hint.XmlAttribute})]
		private String byId;

		public LinkWith()
		{ }

		public String Name
		{
			get{return name;}
			set{name = value;}
		}

		public String ById
		{
			get{return byId;}
			set{byId = value;}
		}

	    #region Implementation of IMappable

	    public String Key()
	    {
	        return Name;
	    }

	    #endregion
	}
}
