//
// ImageDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2012 Interface Ecology Lab. 
//


using Simpl.Fundamental.Generic;
using Simpl.Fundamental.Net;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;
using ecologylab.collections;
using ecologylab.semantics.metadata.builtins;
using ecologylab.semantics.metadata.scalar;
using ecologylab.semantics.metametadata;

namespace ecologylab.semantics.metadata.builtins.declarations 
{
	/// <summary>
	/// The Image Base Class
	/// </summary>
	[SimplInherit]
	public class ImageDeclaration : ClippableDocument<Image>
	{
		/// <summary>
		/// Relative location of local copy of image.
		/// </summary>
		[SimplScalar]
		private MetadataParsedURL localLocation;

		[SimplScalar]
		private MetadataDate creationDate;

		public ImageDeclaration()
		{ }

		public ImageDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public MetadataParsedURL LocalLocation
		{
			get{return localLocation;}
			set
			{
				if (this.localLocation != value)
				{
					this.localLocation = value;
					this.RaisePropertyChanged( () => this.LocalLocation );
				}
			}
		}

		public MetadataDate CreationDate
		{
			get{return creationDate;}
			set
			{
				if (this.creationDate != value)
				{
					this.creationDate = value;
					this.RaisePropertyChanged( () => this.CreationDate );
				}
			}
		}
	}
}
