//
//  CreateAndVisualizeTextSurrogateSemanticAction.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;

namespace ecologylab.semantics.actions 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	[xml_tag("create_and_visualize_text_surrogate")]
    public class CreateAndVisualizeTextSurrogateSemanticAction<IC, SAH> : SemanticAction<IC, SAH>
	{
		public CreateAndVisualizeTextSurrogateSemanticAction()
		{ }
	}
}
