//
//  EvaluateRankWeight.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;

namespace ecologylab.semantics.actions 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	[xml_tag("eval_rank_wt")]
    public class EvaluateRankWeight<IC, SAH> : SemanticAction<IC, SAH> 
	{
		public EvaluateRankWeight()
		{ }
	}
}
