//
//  NestedSemanticAction.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;

namespace ecologylab.semantics.actions 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
    public class NestedSemanticAction<IC, SAH> : SemanticAction<IC, SAH>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplNoWrap]
		[SimplCollection]
		[SimplScope("semantic_action_translation_scope")]
        private List<SemanticAction<IC, SAH>> nestedSemanticActionList;

		public NestedSemanticAction()
		{ }

        public List<SemanticAction<IC, SAH>> NestedSemanticActionList
		{
			get{return nestedSemanticActionList;}
			set{nestedSemanticActionList = value;}
		}
	}
}
