//
//  OrCondition.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;

namespace ecologylab.semantics.actions 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	[xml_tag("or")]
	public class OrCondition : Condition
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_collection]
		[simpl_scope("condition_scope")]
		[simpl_nowrap]
		private List<Condition> checks;

		public OrCondition()
		{ }

		public List<Condition> Checks
		{
			get{return checks;}
			set{checks = value;}
		}
	}
}
