//
//  ConceptGroup.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/05/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;

namespace wikxplorer.messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class ConceptGroup : ElementState
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("concept")]
		private Dictionary<String, Concept> concepts;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String topTitle;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Double averageRelatedness;

		public ConceptGroup()
		{ }

		public Dictionary<String, Concept> Concepts
		{
			get{return concepts;}
			set{concepts = value;}
		}

		public String TopTitle
		{
			get{return topTitle;}
			set{topTitle = value;}
		}

		public Double AverageRelatedness
		{
			get{return averageRelatedness;}
			set{averageRelatedness = value;}
		}
	}
}
