//
//  RelatednessResponse.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/05/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.oodss.messages;

namespace wikxplorer.messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class RelatednessResponse : ResponseMessage<RelatednessRequest>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("target")]
		private Dictionary<String, Concept> targets;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Boolean ok;

		public RelatednessResponse()
		{ }

		public Dictionary<String, Concept> Targets
		{
			get{return targets;}
			set{targets = value;}
		}

		public Boolean Ok
		{
			get{return ok;}
			set{ok = value;}
		}
	}
}
