//
//  SuggestionResponse.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/05/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.oodss.messages;

namespace wikxplorer.messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class SuggestionResponse : ResponseMessage<SuggestionRequest>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Int32 totalSize;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_collection("group")]
		private List<ConceptGroup> groups;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Boolean ok;

		public SuggestionResponse()
		{ }

		public Int32 TotalSize
		{
			get{return totalSize;}
			set{totalSize = value;}
		}

		public List<ConceptGroup> Groups
		{
			get{return groups;}
			set{groups = value;}
		}

		public Boolean Ok
		{
			get{return ok;}
			set{ok = value;}
		}
	}
}
