//
//  SuggestionRequest.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/05/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.oodss.messages;

namespace wikxplorer.messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class SuggestionRequest : RequestMessage<SuggestionRequest>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String source;

		public SuggestionRequest()
		{ }

		public String Source
		{
			get{return source;}
			set{source = value;}
		}
	}
}
