//
//  UpdateContextRequest.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/05/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.oodss.messages;

namespace wikxplorer.messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class UpdateContextRequest : RequestMessage<UpdateContextRequest>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Int32 action;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String title;

		public UpdateContextRequest()
		{ }

		public Int32 Action
		{
			get{return action;}
			set{action = value;}
		}

		public String Title
		{
			get{return title;}
			set{title = value;}
		}
	}
}
