//
// ClippingDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2014 Interface Ecology Lab. 
//


using Ecologylab.BigSemantics.MetaMetadataNS;
using Ecologylab.BigSemantics.MetadataNS;
using Ecologylab.BigSemantics.MetadataNS.Builtins;
using Ecologylab.BigSemantics.MetadataNS.Scalar;
using Ecologylab.Collections;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Ecologylab.BigSemantics.MetadataNS.Builtins.Declarations 
{
	[SimplInherit]
	public class ClippingDeclaration<M> : RichArtifact<M> where M : Metadata
	{
		[SimplComposite]
		[SimplWrap]
		[SimplScope("repository_documents")]
		[MmName("source_doc")]
		private Document sourceDoc;

		[SimplScalar]
		private MetadataString xpath;

		[SimplScalar]
		private MetadataString caption;

		public ClippingDeclaration()
		{ }

		public ClippingDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public Document SourceDoc
		{
			get{return sourceDoc;}
			set
			{
				if (this.sourceDoc != value)
				{
					this.sourceDoc = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}

		public MetadataString Xpath
		{
			get{return xpath;}
			set
			{
				if (this.xpath != value)
				{
					this.xpath = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}

		public MetadataString Caption
		{
			get{return caption;}
			set
			{
				if (this.caption != value)
				{
					this.caption = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}
	}
}
