//
//  CreateSemanticAnchorSemanticAction.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;
using Simpl.Serialization.Attributes;

namespace ecologylab.semantics.actions 
{
    /// <summary>
    /// missing java doc comments or could not find the source file.
    /// </summary>
    [SimplInherit]
    [SimplTag("create_semantic_anchor")]
    public class CreateSemanticAnchorSemanticOperation : SemanticOperation
    {
        public CreateSemanticAnchorSemanticOperation()
        {
        }

        public override string GetOperationName()
        {
            throw new NotImplementedException();
        }

        public override void HandleError()
        {
            throw new NotImplementedException();
        }

        public override object Perform(object obj)
        {
            throw new NotImplementedException();
        }
    }
}
