//
//  IfSemanticAction.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;
using ecologylabSemantics.ecologylab.semantics.actions;

namespace ecologylab.semantics.actions 
{
    /// <summary>
    /// missing java doc comments or could not find the source file.
    /// </summary>
    [SimplInherit]
    [SimplTag("if")]
    public class IfSemanticOperation : NestedSemanticOperation 
    {
        public IfSemanticOperation()
        {
        }

        public override string GetOperationName()
        {
            return SemanticOperationStandardMethods.If;
        }
    }
}
