//
// DocumentMetadataWrap.cs
// s.im.pl serialization
//
// Generated by DotNetTranslator on 10/19/11.
// Copyright 2011 Interface Ecology Lab. 
//


using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;
using ecologylab.collections;
using ecologylab.semantics.metadata;
using ecologylab.semantics.metadata.scalar;

namespace ecologylab.semantics.metadata.builtins 
{
	[SimplInherit]
    [SimplDescriptorClasses(new Type[] { typeof(MetadataClassDescriptor), typeof(MetadataFieldDescriptor) })]
	public class DocumentMetadataWrap : Metadata
	{
		[SimplComposite]
		[SimplScope("repository_documents")]
		private Document document;

		public DocumentMetadataWrap()
		{ }

		public Document Document
		{
			get{return document;}
			set{if (this.document != value) { this.document = value; this.RaisePropertyChanged(() => this.Document); }}
		}
	}
}
