//
//  Document.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 02/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;
using ecologylab.semantics.metadata.scalar;
using ecologylab.semantics.metadata;

namespace ecologylab.semantics.generated.library 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplDescriptorClasses(new Type[] { typeof(MetadataClassDescriptor), typeof(MetadataFieldDescriptor) })]
	[SimplInherit]
	public class Document : ClippableMetadata
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[MmName("location")]
		[SimplScalar]
		private MetadataParsedURL location;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[MmName("title")]
		[SimplScalar]
        [SimplCompositeAsScalar]
		private MetadataString title;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[MmName("description")]
		[SimplScalar]
		private MetadataString description;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplScalar]
		[SimplHints(new Hint[] { Hint.XmlLeaf })]
		private MetadataString query;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[MmName("generation")]
		[SimplScalar]
		private MetadataInteger generation;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[MmName("page_structure")]
		[SimplScalar]
		private MetadataString pageStructure;

        [MmName("favicon")]
        [SimplScalar]
        private MetadataParsedURL favicon;



		public Document()
		{ }

		public MetadataParsedURL Location
		{
			get{return location;}
			set{location = value;}
		}

		public MetadataString Title
		{
			get{return title;}
			set{title = value;}
		}

		public MetadataString Description
		{
			get{return description;}
			set{description = value;}
		}

		public MetadataString Query
		{
			get{return query;}
			set{query = value;}
		}

		public MetadataInteger Generation
		{
			get{return generation;}
			set{generation = value;}
		}

		public MetadataString PageStructure
		{
			get{return pageStructure;}
			set{pageStructure = value;}
		}

        public MetadataParsedURL Favicon
        {
            get { return favicon; }
            set { favicon = value; }
        }

        public override String ToString()
        {
            return (title != null) ? title.Value : base.ToString();
        }
	}   
}
