//
// MediaClipping.cs
// s.im.pl serialization
//
// Generated by DotNetTranslator on 10/19/11.
// Copyright 2011 Interface Ecology Lab. 
//


using System;
using System.Collections;
using System.Collections.Generic;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using ecologylab.semantics.metadata.builtins.declarations;
using ecologylab.semantics.metametadata;

namespace ecologylab.semantics.metadata.builtins 
{
	[SimplInherit]
	public class MediaClipping<ME> : MediaClippingDeclaration<ME> where ME : ClippableDocument<ME>
	{

		public MediaClipping() { }

        public MediaClipping(MetaMetadataCompositeField mmd) : base(mmd) { }

	}
}
