//
//  UserAgent.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;
using Simpl.Serialization;
using Simpl.Serialization.Types.Element;

namespace Ecologylab.BigSemantics.MetaMetadataNS.Net 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class UserAgent : ElementState, IMappable<String>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplScalar]
		private String name;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplTag("string")]
		[SimplScalar]
		private String userAgentString;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplTag("default")]
		[SimplScalar]
		private Boolean defaultAgent;

		public UserAgent()
		{ }

		public String Name
		{
			get{return name;}
			set{name = value;}
		}

		public String UserAgentString
		{
			get{return userAgentString;}
			set{userAgentString = value;}
		}

		public Boolean DefaultAgent
		{
			get{return defaultAgent;}
			set{defaultAgent = value;}
		}

		public String Key()
		{
            return Name;
		}
	}
}
