//
//  SemanticsSite.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;
using Ecologylab.BigSemantics.MetaMetadataNS.IO;

namespace Ecologylab.BigSemantics.Connectors 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
	public class SemanticsSite : BasicSite
	{
		public SemanticsSite()
		{ }
	}
}
