//
//  Clipping.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 02/02/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ecologylab.BigSemantics.MetaMetadataNS;
using Ecologylab.BigSemantics.MetadataNS.Builtins.Declarations;
using Simpl.Fundamental.Net;
using Simpl.Serialization.Attributes;

namespace Ecologylab.BigSemantics.MetadataNS.Builtins 
{
    [SimplInherit]
	public class Clipping<M> : ClippingDeclaration<M>, IClipping<M> where M : Metadata
    {
		public Clipping() { }

		public Clipping(MetaMetadataCompositeField mmd) : base(mmd) { }

        public static void InitMediaClipping<CM>(Clipping<CM> mediaClipping, CM clippedMedia, Document source, Document outlink, String caption, String context) where CM : Metadata
	    {
		    mediaClipping.SourceDoc = source;
		    //Clipping.InitClipping(mediaClipping, outlink, context);
		    if (caption != null)
			    mediaClipping.Caption = new Scalar.MetadataString(caption);
		    mediaClipping.Media = clippedMedia;
	    }

        
	}

    public interface IClipping<out TM> where TM : Metadata
    {
        Document SourceDoc { get; set; }
    }
}
