//
// DocumentMetadataWrap.cs
// s.im.pl serialization
//
// Generated by DotNetTranslator on 10/19/11.
// Copyright 2011 Interface Ecology Lab. 
//


using System;
using System.Collections;
using System.Collections.Generic;
using Ecologylab.BigSemantics.MetaMetadataNS;
using Ecologylab.BigSemantics.MetadataNS.Builtins.Declarations;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;

namespace Ecologylab.BigSemantics.MetadataNS.Builtins 
{
	[SimplInherit]
	public class DocumentMetadataWrap : DocumentMetadataWrapDeclaration
	{

		public DocumentMetadataWrap() { }

		public DocumentMetadataWrap(MetaMetadataCompositeField mmd) : base(mmd) { }

	}
}
