//
//  BasicSite.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;
using ecologylab.serialization.types.element;

namespace ecologylab.io 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[xml_tag("site")]
	public class BasicSite : ElementState, Mappable
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String domain;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Single minDownloadInterval;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Boolean ignoreSemanticBoost;

		public BasicSite()
		{ }

		public String Domain
		{
			get{return domain;}
			set{domain = value;}
		}

		public Single MinDownloadInterval
		{
			get{return minDownloadInterval;}
			set{minDownloadInterval = value;}
		}

		public Boolean IgnoreSemanticBoost
		{
			get{return ignoreSemanticBoost;}
			set{ignoreSemanticBoost = value;}
		}

		public Object key()
		{
            return domain;
		}
	}
}
