//
//  Concept.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/02/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;
using ecologylab.serialization.types.element;

namespace wixplorer.concept 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class Concept : ElementState, Mappable
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String title;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Int32 type;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Double relatedness;

		public Concept()
		{ }

		public String Title
		{
			get{return title;}
			set{title = value;}
		}

		public Int32 Type
		{
			get{return type;}
			set{type = value;}
		}

		public Double Relatedness
		{
			get{return relatedness;}
			set{relatedness = value;}
		}

		public Object key()
		{
			throw new NotImplementedException();
		}
	}
}
