//
//  SuggestedConcepts.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/02/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;

namespace wixplorer.concept 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class SuggestedConcepts : ElementState
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String source;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_collection]
		private List<String> context;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_collection]
		private List<ConceptGroup> groups;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Int32 totalSize;

		public SuggestedConcepts()
		{ }

		public String Source
		{
			get{return source;}
			set{source = value;}
		}

		public List<String> Context
		{
			get{return context;}
			set{context = value;}
		}

		public List<ConceptGroup> Groups
		{
			get{return groups;}
			set{groups = value;}
		}

		public Int32 TotalSize
		{
			get{return totalSize;}
			set{totalSize = value;}
		}
	}
}
