//
//  Metadata.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/02/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;
using ecologylab.semantics.metadata.scalar;
using System.Collections;
using System.Windows.Controls;
using System.Windows;


namespace ecologylab.semantics.metadata 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_descriptor_classes(new Type[] { typeof(MetadataClassDescriptor), typeof(MetadataFieldDescriptor) })]
	public class Metadata : ElementState
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		[xml_other_tags(new String[]{"meta_metadata_name", })]
		[xml_tag("mm_name")]
		private MetadataString metaMetadataName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[semantics_mixin]
		[simpl_collection("mixins")]
		[mm_name("mixins")]
		private List<Metadata> mixins;

		public Metadata()
		{ }

		public MetadataString MetaMetadataName
		{
			get { return metaMetadataName; }
			set { metaMetadataName = value; }
		}

		public List<Metadata> Mixins
		{
			get { return mixins; }
			set { mixins = value; }
		}
	}
}
