//
//  MetadataFieldDescriptor.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;

namespace ecologylab.semantics.metadata 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class MetadataFieldDescriptor : FieldDescriptor
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String mmName;

		public MetadataFieldDescriptor()
		{ }

		public String MmName
		{
			get{return mmName;}
			set{mmName = value;}
		}
	}
}
