//
//  MetaMetadata.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;

using Simpl.Serialization;
using Simpl.Serialization.Types.Element;

namespace ecologylab.semantics.metametadata 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
	public class MetaMetadata : MetaMetadataCompositeField, IMappable
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplComposite]
		private MetaMetadataSelector selector;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplTag("package")]
		[SimplScalar]
		private String packageAttribute;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplScalar]
		private Boolean dontGenerateClass;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplCollection("mixins")]
		[SimplNoWrap]
		private List<String> mixins;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplScalar]
		private String collectionOf;

		public MetaMetadata()
		{ }

        protected override string GetMetaMetadataTagToInheritFrom()
        {
            return extendsAttribute ?? base.GetMetaMetadataTagToInheritFrom();
        }

        #region Properties
        public MetaMetadataSelector Selector
        {
            get { return selector ?? MetaMetadataSelector.NULL_SELECTOR; }
            set { selector = value; }
        }

        public String PackageAttribute
        {
            get { return packageAttribute; }
            set { packageAttribute = value; }
        }

        public Boolean DontGenerateClass
        {
            get { return dontGenerateClass; }
            set { dontGenerateClass = value; }
        }

        public List<String> Mixins
        {
            get { return mixins; }
            set { mixins = value; }
        }

        public String CollectionOf
        {
            get { return collectionOf; }
            set { collectionOf = value; }
        }
        #endregion
    }
}
