//
//  MetaMetadataRepository.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 10/10/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;
using ecologylab.serialization.types;
using ecologylab.semantics.actions;
using ecologylab.semantics.connectors;
using ecologylab.semantics.metametadata;
using ecologylab.net;
using ecologylab.textformat;

namespace ecologylab.semantics.metametadata 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class MetaMetadataRepository : ElementState
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		public String name;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[xml_tag("package")]
		[simpl_scalar]
		public String packageAttribute;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("user_agent")]
		public Dictionary<String, UserAgent> userAgents;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("search_engine")]
		public Dictionary<String, SearchEngine> searchEngines;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("named_style")]
		public Dictionary<String, NamedStyle> namedStyles;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		public String defaultUserAgentName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_nowrap]
		[simpl_collection("cookie_processing")]
		public List<CookieProcessing> cookieProcessors;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("meta_metadata")]
		[simpl_nowrap]
		public Dictionary<String, MetaMetadata> repositoryByTagName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("selector")]
		[simpl_nowrap]
		public Dictionary<String, MetaMetadataSelector> selectorsByName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("site")]
		public Dictionary<String, SemanticsSite> sites;

		public MetaMetadataRepository()
		{ }
	}
}
