//
//  MetaMetadataRepository.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;
using ecologylab.net;
using ecologylab.semantics.connectors;
using ecologylab.textformat;

namespace ecologylab.semantics.metametadata 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class MetaMetadataRepository : ElementState
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String name;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[xml_tag("package")]
		[simpl_scalar]
		private String packageAttribute;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("user_agent")]
		private Dictionary<String, UserAgent> userAgents;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("search_engine")]
		private Dictionary<String, SearchEngine> searchEngines;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("named_style")]
		private Dictionary<String, NamedStyle> namedStyles;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String defaultUserAgentName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_nowrap]
		[simpl_collection("cookie_processing")]
		private List<CookieProcessing> cookieProcessors;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("meta_metadata")]
		[simpl_nowrap]
		private Dictionary<String, MetaMetadata> repositoryByTagName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("selector")]
		[simpl_nowrap]
		private Dictionary<String, MetaMetadataSelector> selectorsByName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_map("site")]
		private Dictionary<String, SemanticsSite> sites;

		public MetaMetadataRepository()
		{ }

		public String Name
		{
			get{return name;}
			set{name = value;}
		}

		public String PackageAttribute
		{
			get{return packageAttribute;}
			set{packageAttribute = value;}
		}

		public Dictionary<String, UserAgent> UserAgents
		{
			get{return userAgents;}
			set{userAgents = value;}
		}

		public Dictionary<String, SearchEngine> SearchEngines
		{
			get{return searchEngines;}
			set{searchEngines = value;}
		}

		public Dictionary<String, NamedStyle> NamedStyles
		{
			get{return namedStyles;}
			set{namedStyles = value;}
		}

		public String DefaultUserAgentName
		{
			get{return defaultUserAgentName;}
			set{defaultUserAgentName = value;}
		}

		public List<CookieProcessing> CookieProcessors
		{
			get{return cookieProcessors;}
			set{cookieProcessors = value;}
		}

		public Dictionary<String, MetaMetadata> RepositoryByTagName
		{
			get{return repositoryByTagName;}
			set{repositoryByTagName = value;}
		}

		public Dictionary<String, MetaMetadataSelector> SelectorsByName
		{
			get{return selectorsByName;}
			set{selectorsByName = value;}
		}

		public Dictionary<String, SemanticsSite> Sites
		{
			get{return sites;}
			set{sites = value;}
		}
	}
}
