//
//  MetaMetadataSelector.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;
using ecologylab.serialization.types.element;
using ecologylab.net;

namespace ecologylab.semantics.metametadata 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class MetaMetadataSelector : ElementState, Mappable
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String name;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String prefName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String defaultPref;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private ParsedUri urlStripped;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private ParsedUri urlPathTree;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private System.Text.RegularExpressions.Regex urlRegex;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String domain;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_collection("mime_type")]
		[simpl_nowrap]
		private List<String> mimeTypes;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_collection("suffix")]
		[simpl_nowrap]
		private List<String> suffixes;

        public static MetaMetadataSelector NULL_SELECTOR = new MetaMetadataSelector();

		public MetaMetadataSelector()
		{ }

        #region Properties
        
        public String Name
		{
			get{return name;}
			set{name = value;}
		}

		public String PrefName
		{
			get{return prefName;}
			set{prefName = value;}
		}

		public String DefaultPref
		{
			get{return defaultPref;}
			set{defaultPref = value;}
		}

		public ParsedUri UrlStripped
		{
			get{return urlStripped;}
			set{urlStripped = value;}
		}

		public ParsedUri UrlPathTree
		{
			get{return urlPathTree;}
			set{urlPathTree = value;}
		}

		public System.Text.RegularExpressions.Regex UrlRegex
		{
			get{return urlRegex;}
			set{urlRegex = value;}
		}

		public String Domain
		{
			get{return domain;}
			set{domain = value;}
		}

		public List<String> MimeTypes
		{
			get{return mimeTypes;}
			set{mimeTypes = value;}
		}

		public List<String> Suffixes
		{
			get{return suffixes;}
			set{suffixes = value;}
		}
        #endregion
        
        public Object key()
		{
            return name;
		}
	}
}
