//
// ClippingDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2012 Interface Ecology Lab. 
//


using Ecologylab.Collections;
using Ecologylab.Semantics.MetaMetadataNS;
using Ecologylab.Semantics.MetadataNS;
using Ecologylab.Semantics.MetadataNS.Builtins;
using Ecologylab.Semantics.MetadataNS.Scalar;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Ecologylab.Semantics.MetadataNS.Builtins.Declarations 
{
	[SimplInherit]
	public class ClippingDeclaration : Metadata
	{
		[SimplScalar]
		private MetadataString context;

		[SimplScalar]
		[SimplHints(new Hint[] {Hint.XmlLeafCdata})]
		private MetadataString contextHtml;

		[SimplScalar]
		private MetadataString xpath;

		[SimplComposite]
		[SimplWrap]
		[SimplScope("repository_documents")]
		[MmName("source_doc")]
		private Document sourceDoc;

		[SimplComposite]
		[SimplWrap]
		[SimplScope("repository_documents")]
		[MmName("outlink")]
		private Document outlink;

		public ClippingDeclaration()
		{ }

		public ClippingDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public MetadataString Context
		{
			get{return context;}
			set
			{
				if (this.context != value)
				{
					this.context = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}

		public MetadataString ContextHtml
		{
			get{return contextHtml;}
			set
			{
				if (this.contextHtml != value)
				{
					this.contextHtml = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}

		public MetadataString Xpath
		{
			get{return xpath;}
			set
			{
				if (this.xpath != value)
				{
					this.xpath = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}

		public Document SourceDoc
		{
			get{return sourceDoc;}
			set
			{
				if (this.sourceDoc != value)
				{
					this.sourceDoc = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}

		public Document Outlink
		{
			get{return outlink;}
			set
			{
				if (this.outlink != value)
				{
					this.outlink = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}
	}
}
