//
// DocumentMetadataWrapDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2014 Interface Ecology Lab. 
//


using Ecologylab.Collections;
using Ecologylab.Semantics.MetaMetadataNS;
using Ecologylab.Semantics.MetadataNS;
using Ecologylab.Semantics.MetadataNS.Builtins;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Ecologylab.Semantics.MetadataNS.Builtins.Declarations 
{
	/// <summary>
	/// Used to disambiguated Document subclass composites.
	/// </summary>
	[SimplInherit]
	public class DocumentMetadataWrapDeclaration : Metadata
	{
		/// <summary>
		/// polymorphic across documents
		/// </summary>
		[SimplComposite]
		[SimplScope("repository_documents")]
		[MmName("document")]
		private Document document;

		public DocumentMetadataWrapDeclaration()
		{ }

		public DocumentMetadataWrapDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public Document Document
		{
			get{return document;}
			set
			{
				if (this.document != value)
				{
					this.document = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}
	}
}
