//
// ImageDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2013 Interface Ecology Lab. 
//


using Ecologylab.Collections;
using Ecologylab.Semantics.MetaMetadataNS;
using Ecologylab.Semantics.MetadataNS.Builtins;
using Ecologylab.Semantics.MetadataNS.Scalar;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Ecologylab.Semantics.MetadataNS.Builtins.Declarations 
{
	/// <summary>
	/// The Image Base Class
	/// </summary>
	[SimplInherit]
	public class ImageDeclaration : ClippableDocument<Image>
	{
		[SimplScalar]
		private MetadataDate creationDate;

		public ImageDeclaration()
		{ }

		public ImageDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public MetadataDate CreationDate
		{
			get{return creationDate;}
			set
			{
				if (this.creationDate != value)
				{
					this.creationDate = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}
	}
}
