//
// TextSelfmadeDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2014 Interface Ecology Lab. 
//


using Ecologylab.Collections;
using Ecologylab.Semantics.MetaMetadataNS;
using Ecologylab.Semantics.MetadataNS.Builtins;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Ecologylab.Semantics.MetadataNS.Builtins.Declarations 
{
	[SimplInherit]
	public class TextSelfmadeDeclaration : RichArtifact<HtmlText>
	{
		public TextSelfmadeDeclaration()
		{ }

		public TextSelfmadeDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }

	}
}
