//
// AnnotationDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2012 Interface Ecology Lab. 
//


using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;
using ecologylab.collections;
using ecologylab.semantics.metadata;
using ecologylab.semantics.metadata.builtins;
using ecologylab.semantics.metadata.scalar;
using ecologylab.semantics.metametadata;

namespace ecologylab.semantics.metadata.builtins.declarations 
{
	[SimplInherit]
	public class AnnotationDeclaration : Metadata
	{
		[SimplScalar]
		private MetadataString text;

		[SimplScalar]
		private MetadataString author;

		[SimplScalar]
		private MetadataDate creationTime;

		public AnnotationDeclaration()
		{ }

		public AnnotationDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public MetadataString Text
		{
			get{return text;}
			set
			{
				if (this.text != value)
				{
					this.text = value;
					this.RaisePropertyChanged( () => this.Text );
				}
			}
		}

		public MetadataString Author
		{
			get{return author;}
			set
			{
				if (this.author != value)
				{
					this.author = value;
					this.RaisePropertyChanged( () => this.Author );
				}
			}
		}

		public MetadataDate CreationTime
		{
			get{return creationTime;}
			set
			{
				if (this.creationTime != value)
				{
					this.creationTime = value;
					this.RaisePropertyChanged( () => this.CreationTime );
				}
			}
		}
	}
}
