//
// DebugMetadataDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2012 Interface Ecology Lab. 
//


using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using ecologylab.collections;
using ecologylab.semantics.metadata;
using ecologylab.semantics.metadata.builtins;
using ecologylab.semantics.metadata.scalar;
using ecologylab.semantics.metametadata;

namespace ecologylab.semantics.metadata.builtins.declarations 
{
	[SimplInherit]
	public class DebugMetadataDeclaration : Metadata
	{
		[SimplScalar]
		private MetadataStringBuilder newTermVector;

		public DebugMetadataDeclaration()
		{ }

		public DebugMetadataDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public MetadataStringBuilder NewTermVector
		{
			get{return newTermVector;}
			set
			{
				if (this.newTermVector != value)
				{
					this.newTermVector = value;
					this.RaisePropertyChanged( () => this.NewTermVector );
				}
			}
		}
	}
}
