//
// DocumentMetadataWrapDeclaration.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2012 Interface Ecology Lab. 
//


using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;
using ecologylab.collections;
using ecologylab.semantics.metadata;
using ecologylab.semantics.metadata.builtins;
using ecologylab.semantics.metametadata;

namespace ecologylab.semantics.metadata.builtins.declarations 
{
	/// <summary>
	/// Used to disambiguated Document subclass composites.
	/// </summary>
	[SimplInherit]
	public class DocumentMetadataWrapDeclaration : Metadata
	{
		/// <summary>
		/// polymorphic across documents
		/// </summary>
		[SimplComposite]
		[SimplScope("repository_documents")]
		[MmName("document")]
		private Document document;

		public DocumentMetadataWrapDeclaration()
		{ }

		public DocumentMetadataWrapDeclaration(MetaMetadataCompositeField mmd) : base(mmd) { }


		public Document Document
		{
			get{return document;}
			set
			{
				if (this.document != value)
				{
					this.document = value;
					this.RaisePropertyChanged( () => this.Document );
				}
			}
		}
	}
}
