//
//  NestedSemanticAction.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;

namespace Ecologylab.BigSemantics.Actions 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
    public class NestedSemanticOperation : SemanticOperation
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplNoWrap]
		[SimplCollection]
		[SimplScope("semantic_action_translation_scope")]
        private List<SemanticOperation> nestedSemanticActionList;

        public NestedSemanticOperation()
		{ }

        public List<SemanticOperation> NestedSemanticActionList
		{
			get{return nestedSemanticActionList;}
			set{nestedSemanticActionList = value;}
		}

	    public override String GetOperationName()
	    {
		    return null;
	    }

        public override void HandleError()
        {
        }

        public override Object Perform(Object obj)
        {
            return null;
        }

        public override void SetNestedOperationState(String name, Object value)
	    {
		    foreach (SemanticOperation action in nestedSemanticActionList)
		    {
                SemanticOperationHandler handler = SemanticOperationHandler;
                action.SemanticOperationHandler = handler;
			    handler.SetOperationState(action, name, value);
                action.SetNestedOperationState(name, value);
		    }
	    }
	}
}
