//
//  SetMetadataSemanticAction.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 11/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Serialization.Attributes;
using Ecologylab.BigSemantics.Actions;

namespace Ecologylab.BigSemantics.Actions 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
	[SimplTag("set_metadata")]
    public class SetMetadataSemanticOperation : SemanticOperation 
	{
		public SetMetadataSemanticOperation()
		{ }

	    public override string GetOperationName()
	    {
            return SemanticOperationStandardMethods.SetMetadata;
	    }

	    public override void HandleError()
	    {
	    }

	    public override object Perform(object obj)
	    {
            throw new Exception("Andruid decided this is no longer part of semantics in tng. Instead, pass a source_document argument to parse_document or create_image_surrogate!");
	    }
	}
}
