//
//  Image.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 02/02/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Ecologylab.Semantics.Collecting;
using Ecologylab.Semantics.MetaMetadataNS;
using Ecologylab.Semantics.MetadataNS.Builtins.Declarations;
using Simpl.Serialization.Attributes;
using Ecologylab.Semantics.MetadataNS.Scalar;
using Ecologylab.Semantics.MetadataNS;

namespace Ecologylab.Semantics.MetadataNS.Builtins 
{
	[SimplInherit]
	public class Image : ImageDeclaration
	{

		public Image()
		{ }

        public Image(MetaMetadataCompositeField metaMetadata) : base(metaMetadata) { }

        public ImageClipping ConstructClipping(Document sourceDocument, Document outlink, String caption, String context)
	    {
		    var result	= new ImageClipping(SemanticsSessionScope.Get.ImageClippingMetaMetadata, this, sourceDocument, outlink, caption, context);
		    this.AddClipping(result);
		
		    return result;
	    }

        public override bool IsImage
        {
            get { return true; }
        }
	}
}
