//
// TextClipping.cs
// s.im.pl serialization
//
// Generated by DotNetTranslator on 10/19/11.
// Copyright 2011 Interface Ecology Lab. 
//


using Ecologylab.Semantics.MetaMetadataNS;
using Ecologylab.Semantics.MetadataNS.Builtins.Declarations;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;
using Ecologylab.Collections;
using Ecologylab.Semantics.MetadataNS;
using Ecologylab.Semantics.MetadataNS.Scalar;

namespace Ecologylab.Semantics.MetadataNS.Builtins 
{
	[SimplInherit]
	public class TextClipping : TextClippingDeclaration
	{

		public TextClipping() { } 

		public TextClipping(MetaMetadataCompositeField mmd) : base(mmd) { }

	}
}
